### PR TITLE
Babel 5 rather than Webpack

### PR DESCRIPTION
**Pull request by justin808**
@ikrtolica, @dylangrafmyre We'll use Babel 5, without Webpack. I had a detailed conversation about this with @alexfedoseev. The problems we faced with async/await were due to Babel 6.

There's a few slight advantages to not using Webpack:
- node-inspector (node-debugger command) works seemingly smoother in case we need to use it.
- less complexity that could causes issues later.

We dug up the latest babel 5 versions and they seem to work fine.

### CODE REVIEW

**Comment by dylangrafmyre** [comment]
@justin808 How can you and @alex say the issues we had with async/await where due to Babel 6? Is it Babel 6 itself or the config is different between webpack and babel5/babel6?

Using `babel-polyfill` and adding the presets to `babel-loader` webpack config caused async/await  to work just fine with Babel 6.

**Comment by alex35mil** [comment]
@dylangrafmyre Let me expand the reasons. Usually I add webpack layer to server-side flow in 2 cases:
1. When I want to get isolated scope for each http request (node modules are singletons by their nature, so we can get data leak between requests).
2. When I use CSS Modules in isomorphic app.

In the case of server tool webpack gives us no benefits, but another one thing to handle & support (for example we need to make sure that all global node properties are provided in `node` section of webpack config, we need to make sure we're not bundling node's core and npm modules with all binaries into the bundle etc.). So if there is no profit here, I suggest to remove this layer and compile node modules directly with babel.

When we use babel@6 directly from the CLI, it bundles all the things, but in runtime it throws with message that `regeneratorRuntime` is not defined. With the same babel@5 setup it works. (Yes we applied `babel-polyfill`, yes we adapted `.babelrc` etc.). Taking into account the fact that babel@6 is really alpha release, we decided not shaving yak here and rollback to stable 5.x version until 6 branch will become more or less stable.

**Comment by dylangrafmyre** [comment]
@alexfedoseev I agree with your points about webpack for you version of server-side flow. However, I am using it in a different context. Probably something that was not discussed with @justin808.

My context is using webpack to watch and re-generate the bundle on edit to code and have nodemon restart server and run bundle for live output of code changes while developing server-side applications.

https://github.com/shakacode/node-webpack-async-example/blob/babel-6-examples/gulpfile.babel.js

But I imagine I could just do the same thing possibly with out webpack? Using just gulp, babel, and nodemon? Have nodemon do the watching the source directory for changes and run babel to generate updated code and restart server to run main js file?

Your thoughts? THanks Alex!

**Comment by alex35mil** [comment]
@dylangrafmyre From what I see, you don't need gulp or webpack here. Have you tried to run it with cli and `babel-node`? https://babeljs.io/docs/setup/#nodemon

**Comment by dylangrafmyre** [comment]
@alexfedoseev yes the above works when are are working within your source code. But maybe I am looking at this wrong? For my Adobe photoshop plugin i am copying two files into the photoshop generator directory `package.json` and `main.js`. `main.js` is my transpiled code. 

Therefore what I really want to watch and reload each time there is a code edit to the source code is the transpiled code file. I want a new generated file, node restarted with the new file to verify changes from the transpiled file.

I understand that is what babel-node is doing. Transpiling on the fly and running your code. But is there any divergence ever with when the transpiled code is output to a file?. That file working properly is my main concern.

**Comment by dylangrafmyre** [comment]
@alexfedoseev nevermind, it looks like it works if I point nodemon to the path of the transpiled file with babel-node and work within the source code.

**Comment by alex35mil** [comment]
@dylangrafmyre I don't think there is any divergence here (if there is any, it's a bug), `babel-node` uses the same core modules to transpile code, but it passes result to node from memory instead of from file. I'm using `babel-node` quite often for server-side development, don't remember any issue with it.

I had such concern with development & production code for the client. I tried to use same config with a little difference in `process.env.NODE_ENV` variable for libs. But in this case I can't extract my css in separate file for production or I can't have hot reloadable styles for development. So I just accept different workflows :)

**Pull request merged**
